<?php

use Drupal\Core\Entity\EntityFormInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\entity_field_form_require\EntityFieldFormRequire;
use Drupal\field\Entity\FieldConfig;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add checkboxed to manage form display UI to make the field required.
 */
function entity_field_form_require_form_entity_form_display_edit_form_alter(array &$form, FormStateInterface $form_state) {
  // TODO Add checkboxes to each field to make required in this mode.
  // TODO Add submit handler to save the required settings.
}

/**
 * Implements hook_form_alter().
 */
function entity_field_form_require_form_alter(array &$form, FormStateInterface $form_state) {
  $form_object = $form_state->getBuildInfo()['callback_object'] ?? NULL;
  if (!$form_object instanceof EntityFormInterface) {
    return;
  }

  // This is an entity form, so it may have fields that need to be marked
  // required.  Proceed with looking for such.
  $required_fields = &drupal_static(__FUNCTION__);
  if (!isset($required_fields)) {
    $required_fields = \Drupal::moduleHandler()
      ->invokeAll('entity_field_form_require_field_info');
  }
  $display_mode = $form_state->getStorage()['form_display']->get('mode');
  foreach ($form_object->getEntity()->getFields() as $field) {
    $field_definition = $field->getFieldDefinition();
    if ($field_definition instanceof FieldConfig) {
      $name = $field_definition->get('field_name');
      if (!array_key_exists($name, $required_fields)) {
        continue;
      }
      $field_display_id = $field_definition->getTargetEntityTypeId() . '.' . $field_definition->getTargetBundle() . ".$display_mode";
      $should_be_required = in_array($field_display_id, $required_fields[$name]['#required']['display_ids']);
      if ($should_be_required) {
        // TODO I'm not sure $form[$name] is the correct way to select the element in all cases, what if nested or grouped?
        EntityFieldFormRequire::makeElementRequired($form[$name], $form_state);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Disable field #required in field config UI if being required by a form mode.
 */
function entity_field_form_require_form_field_config_edit_form_alter(array &$form, FormStateInterface $form_state) {
  $required_fields = \Drupal::moduleHandler()
    ->invokeAll('entity_field_form_require_field_info');
  $form_display = $form_state->getBuildInfo()['callback_object']->getEntity();
  $field_name = $form_display->getFieldStorageDefinition()->getName();
  if (empty($required_fields[$field_name]['#required']['display_ids'])) {
    return;
  }
  $entity_type_id = $form_display->getTargetEntityTypeId();
  $bundle = $form_display->getTargetBundle();
  $look_for_prefix = "$entity_type_id.$bundle";
  $matches = array_filter($required_fields[$field_name]['#required']['display_ids'], function ($item) use ($look_for_prefix) {
    return strpos($item, $look_for_prefix) === 0;
  });
  if (!empty($matches)) {
    $form['required']['#disabled'] = TRUE;
    $form['required']['#description'] = t('This field is required by one or more form displays and cannot be changed here.  See the entity_field_form_require module for more info.');
  }
}
